{% set name = "cytoplay" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3ffbdb8ec4503c27075a578dfb5c6cbd487c2291319f02e4babd44b5696c7815
build:
  skip: true  # [win]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  

requirements:
  build:
    - cmake >=3.14
    - make 
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - libblas
    - liblapack
    - pybind11
    - freeglut  # [linux]
    - libglvnd-glx-cos7-x86_64  # [linux]
    - xorg-libxi
    - xorg-libxmu
    - glew
    - zlib  # [macOS]
    - libglx  # [linux]
    - libglvnd  # [linux]
  host:
    - setuptools
    - python
    - libblas
    - liblapack
    - pybind11
    - freeglut  # [linux]
    - libglx  # [linux]
    - libglvnd-glx-cos7-x86_64  # [linux]
    - xorg-libxi
    - xorg-libxmu
    - glew
    - zlib  # [macOS]
    - libglx  # [linux]
    - libglvnd  # [linux]
  run:
    - python
    - libblas
    - liblapack
    - pybind11
    - freeglut  # [linux]
    - xorg-libxi
    - xorg-libxmu
    - glew
    - mesalib
    - zlib  # [macOS]
    - libglx  # [linux]

test:
  imports:
    - cytosim
about:
  home: http://cytosim.org/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "Cytosim: Langevin dynamics of active polymer networks"
  doc_url: https://cytosim.gitlab.io/cytosim/doc/code/doxygen/index.html
  dev_url: https://gitlab.com/f-nedelec/cytosim

extra:
  recipe-maintainers:
    - SergeDmi
