{% set name = "cytoplay" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ac25e27310ebe3753432b266518537bba80065c27da2c12d6c3ad658709e3fd
build:
  skip: true  # [win]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  

requirements:
  build:
    - cmake >=3.14
    - make 
    - {{ compiler('cxx') }}
    - libblas
    - liblapack
    - pybind11
    - freeglut
    - xorg-libxi
    - xorg-libxmu
    - glew
    - mesalib
    - mesa-libgl-cos7-x86_64
    
  host:
    - setuptools
    - python
    - libblas
    - liblapack
    - pybind11
    - freeglut
    - xorg-libxi
    - xorg-libxmu
    - glew
    - mesalib
    - mesa-libgl-cos7-x86_64
  run:
    - python
    - libblas
    - liblapack
    - pybind11
    - freeglut
    - xorg-libxi
    - xorg-libxmu
    - glew
    - mesalib

test:
  imports:
    - cytosim
about:
  home: http://cytosim.org/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "Cytosim: Langevin dynamics of active polymer networks"
  doc_url: https://cytosim.gitlab.io/cytosim/doc/code/doxygen/index.html
  dev_url: https://gitlab.com/f-nedelec/cytosim

extra:
  recipe-maintainers:
    - SergeDmi
